### ISSUE TITLE
Prevent recording of searches?

### ISSUE THREAD

**Issue by Post169** [Rob--W/dont-track-me-google#24]
DTMG does a great job of reversing the transformation by Google of original URLs into URLs that take me on a detour that enables tracking!

However, I understand that Google also records what I search for, and I don't see anything about blocking that on the description of this extension.

Could you add that, or notify me if you know of an extension that already does it?

Thanks!

**Comment by Rob--W** [comment]
> However, I understand that Google also records what I search for, and I don't see anything about blocking that on the description of this extension.

There is no way to guarantee that searches are not recorded (because Google can already connect the search query with your profile the moment the search query is sent to Google's servers). The only way to not be tracked at all by Google is to not use Google.

Any extension that promises otherwise only gives a false sense of privacy. That's why I don't promise that the extension completely stops tracking. Though if easy ways are available to reduce the amount of tracking, I will add it. For example, in version 4.12 I block several instances of tracking (see #20).

PS. the primary purpose of this script/extension is to improve the usability of Google, by ensuring that links are not ugly. Blocking tracking is a desired side-effect/feature, but not the main feature because nobody can guarantee that you won't be tracked as long as you willingly send search queries to Google.

**Comment by ioc2e3** [comment]
> ... ，因為只要您主動向 Google 發送搜尋查詢，就沒有人能保證您不會被追蹤。

This is ...

Very unfortunate thing ...

.
