### ISSUE TITLE
google serp still track you via HTML “ping” attribute

### ISSUE THREAD

**Issue by fghhfg** [Rob--W/dont-track-me-google#33]
In google.com

> Google uses different techniques in different browsers to make this type of tracking possible.

In Chrome, 
the new HTML “ping” attribute

![chrome-google-ping-link](https://user-images.githubusercontent.com/1284845/53707644-c4c1c700-3e6a-11e9-9119-20bd6a393971.png)

ref:
https://www.eff.org/deeplinks/2018/10/privacy-badger-now-fights-more-sneaky-google-tracking

and almost every adblock-like app does not block this...

---
I add this on my filter:

    ||google.*/url?sa$~xmlhttprequest

**Comment by Rob--W** [comment]
The primary purpose of the extension is to prevent the link from becoming unreadable. I already remove the `ping` attribute for certain versions of the search result page: https://github.com/Rob--W/dont-track-me-google/blob/a37a5b2495935dee74b527fb6794240f57ec840c/contentscript.js#L49-L50

Perhaps I should extend it to every link. The snippet above only activates when the mouse is used; if I decide to extend it to all links, then I should also add it to the click handler, so that the logic is also run when the search results are activated by keyboard.

On the other hand, as said before, my extension's primary purpose is to make sure that the link itself is clean (and not an intermediate tracking URL). There are already other extensions to block `<a ping>` on all websites, not just Google, such as uBlock Origin: https://github.com/gorhill/uBlock/wiki/Disable-hyperlink-auditing-beacon

**Comment by Rob--W** [comment]
> Where can we find ONE simple Google result cleanup (ads and tracking?)

If avoidance of tracking is a hard requirement, then the solution is to not use Google.
https://startpage.com/ is a privacy-friendly alternative to Google. Startpage uses Google to provide search results, without leaking user data.
Another alternative is DuckDuckGo, but the quality of its search results may differ from what you're used to.

**Comment by Rob--W** [comment]
Fixed in version 4.23 and published (pending review, so not visible to the public yet).

**Comment by Rob--W** [comment]
This feature is opt-out, in case users want to disable it. The description is:

> As of version 4.23 (January 2021), link tracking via the "ping" attribute is disabled by default. This prevents Google from tracking your link clicks. If you want Google to track your link clicks, visit the options page to disable this feature.
