### ISSUE TITLE
Link on Google Calendar is not immediately sanitized

### ISSUE THREAD

**Issue by rmccu** [Rob--W/dont-track-me-google#37]
It looks like links in the GCal are not being modified to strip the google tracking.

Here is a screenshot showing the hover over the location:
![Screen Shot 2020-06-24 at 3 09 35 PM](https://user-images.githubusercontent.com/5711475/85628065-bdf52f80-b62c-11ea-990c-ba5e4391dc8a.png)

And hovering over a body link:
![Screen Shot 2020-06-24 at 3 10 13 PM](https://user-images.githubusercontent.com/5711475/85628122-d49b8680-b62c-11ea-940e-25bdf9eb8363.png)

**Comment by Rob--W** [comment]
I just checked, and Google Calender retrieves the source code (HTML) for the link directly from the server. Because my extension only rewrites links that are created in the browser, it doesn't immediately catch this. I can change the implementation, but that will add some overhead.

Note that as soon as you try to interact with the link (e.g. clicking or right-clicking on the link), the link is sanitized. Is this good enough for you?

**Comment by rmccu** [comment]
Ok, as long as it sanitizes it. I am fine. Thanks!
