### ISSUE TITLE
Presenter View in Google Slides doesn't load.

### ISSUE THREAD

**Issue by BartBlaak** [Rob--W/dont-track-me-google#49]

**Comment by Rob--W** [comment]
Reproduction steps:

1. Open a presentation, e.g. https://docs.google.com/presentation/d/1vpcH6pyFIbzYqS8KvXNWNvwWbc0XvFFgKX0g9pjP6Hs/edit
2. Click on the triangle next to the Slideshow button, and click on the "Presenter view" button.
3. Google Docs should render the slides in full screen AND open a popup.
4. Look at the popup's content.

Expected:
- It should render the speaker notes in the popup.

Actual:
- The new window is blank.

More info:
- Until this is fixed, a workaround is to enter the settings of the extension, and turn off "Clear HTTP referrer (this prevents other sites from seeing your Google search terms)"

**Comment by Rob--W** [comment]
This bug is happening because Docs calls `window.open("about:blank", ...)`, and `about:blank` is considered cross-origin by https://github.com/Rob--W/dont-track-me-google/blob/abffd08f6e0d6eacd42b3ff0ccda1b6838788949/contentscript.js#L409.

Consequently, `noreferrer` is added, which implies `noopener`, which prevents Docs from writing content to the new popup window.

**Comment by Rob--W** [comment]
I have created a fix for the issue. I'll wait a few days to allow for further feedback, and then publish an update.
