### ISSUE TITLE
"Write a review" not working

### ISSUE THREAD

**Issue by bryce-lynch** [Rob--W/dont-track-me-google#5]
When you search for a brand on Google you have a box on the right side where you can enter reviews. There's a button "write a review" which doesn't do anything at all when clicked when this addon is enabled in Firefox.

**Comment by Rob--W** [comment]
Which version of the add-on are you using? Versions 4.8 until version 4.10 contained a bug/feature that prevented links from being handled by the page (defaulting to the browser's default action).

If you are using a recent version, can you show a screenshot of what you mean? I don't see a way to write reviews, but maybe that's because I'm not logged in (or using Google from another country?).

**Comment by bryce-lynch** [comment]
I'm using 4.11. Just tried again: the button only works when the addon is disabled.

**Comment by bryce-lynch** [comment]
Here's an example where the review button are shown: https://www.google.com/#q=ctp+napoli

**Comment by Rob--W** [comment]
Can you include a screenshot and highlight the point of interest? Google does not always look the same in every country.

**Comment by bryce-lynch** [comment]
Screenshot here (the part in red, "write a review", on the bottom right): http://i.imgur.com/HN2xTgw.jpg

**Comment by bryce-lynch** [comment]
Just tried the new version, it works now :) Thanks!
