### ISSUE TITLE
Amazon "sort by" on FireFix broken

### ISSUE THREAD

**Issue by redhermes** [Rob--W/dont-track-me-google#55]
When enabled, dont-track-me-google breaks the "sort-by" feature of on amazon.com. Problem disappears when extension is disabled.  

To repo: go to amazon.com and search for a product. On the sort-by combo box (drop down) change from featured to anything else. The page is refreshed but stays on featured.

**Comment by Rob--W** [comment]
That would be rather unlikely. The extension only works on Google. It does not even have the permission to change behavior on Amazon.

**Comment by redhermes** [comment]
Thanks for the quick answer. (and also for creating this extension) 
I did some more testing and I can reproduce it on demand.  I discovered that I don't have to disable the extension, if I clear the checkbox labeled "Clear HTTP referrer" the problem stops. No other changes. Please try it yourself it only takes a couple of seconds to test. If you can't repo., then it must be interference with another of my extensions.

**Comment by Rob--W** [comment]
Can you provide the exact details to reproduce the issue? Start from a new (empty) Firefox profile, and then explain the steps that you are taking to reach this issue. If it makes it easier, create a screen recording while you are going through the steps to reproduce the issue, and attach the video here.

I still stand by my previous statement of it being not an issue with my extension, because it does not do anything on Amazon. It [only runs code on Google sites](https://github.com/Rob--W/dont-track-me-google/blob/5f439e62a317e42ec945c91a404cbcac2a275530/manifest.json#L13-L210), nowhere else. When I visit Amazon.com, I don't see it embedding any `google.com` webpages, which rules out the possibility of indirect interference.

The "Clear HTTP referrer" option only changes the behavior of anything opened from Google.com. It makes sure that the websites that you're accessing through Google cannot see the search terms that you are visiting from Google. That would be comparable to visiting the website directly from the location bar.

**Comment by redhermes** [comment]
OK, my apologizes you are correct. The problem was with another extension and the issue was masked by the browser reload I did when checking my extensions.
